### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by liyiming22** [XNAL/ReadMore#12]
您好，我把你的项目clone下来，npm install 后，npm run dev发现报错：
```
> Listening at http://localhost:8080

(node:13372) UnhandledPromiseRejectionWarning: Error: Exited with code 4
    at ChildProcess.<anonymous> (/home/yeoman/文档/learn-projects/ReadMore/node_modules/opn/index.js:83:13)
    at Object.onceWrapper (events.js:285:13)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Socket.stream.socket.on (internal/child_process.js:401:11)
    at Socket.emit (events.js:197:13)
    at Pipe._handle.close (net.js:611:12)
(node:13372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:13372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

OS: Linux (4.19.30-1-MANJARO)
node: v11.11.0
npm: 6.9.0

新手，第一次看见这种错误，暂时不知道如何解决。。网上找了一圈也没发现解决方案，是我的版本太新了么？

**Comment by YeomanLi** [comment]
解决了，是`opn`这个包太旧了，我重新安装了新版本的就可以了

**Comment by liyiming22** [comment]
解决了，是`opn`这个包太旧了，我重新安装了新版本的就可以了
